name: Check Signed Commits

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  check-signed-commits-pr:
    name: Check signed commits in PR
    if: ${{ github.event_name == 'pull_request_target' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check signed commits in PR
        uses: 1Password/check-signed-commits-action@v1
